In [14]:
import pandas as pd
import numpy as np

In [18]:
dfd = pd.read_csv(r'C:\Users\arceb\PycharmProjects\pythonProject/Paris.csv', index_col = 0)
dfd=dfd.rename(columns={'Code INSEE commune logt souhaité': 'Code Géographique'})
dfd

C:\Users\arceb\AppData\Local\Temp\ipykernel_40984\4287902780.py:1: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dfd = pd.read_csv(r'C:\Users\arceb\PycharmProjects\pythonProject/Paris.csv', index_col = 0)

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Ressources mensuelles du foyer,"RFR du foyer, année n-1","RFR du foyer, année n-2",Code Géographique,Commune logement souhaité,Montant maxi (loyer+charges) supportable,Sexe demandeur\n,Nationalité demandeur\n,Autre logement dé\ntenu demandeur\n,Nb de personnes handicapees
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,1499.0,NaN,NaN,75056,Paris,650.0,M,Hors Union Européenne,Non,0.0
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,1127.0,11932.0,10817.0,75105,Paris 5ème arrondissement,520.0,M,Française,Non,0.0
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,1501.0,NaN,NaN,75056,Paris,900.0,M,Hors Union Européenne,Non,0.0
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,674.0,0.0,NaN,75113,Paris 13ème arrondissement,800.0,F,Française,Non,0.0
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,3150.0,38081.0,NaN,75103,Paris 3ème arrondissement,1250.0,M,Française,Non,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,433.0,0.0,0.0,75101,Paris 1er arrondissement,350.0,M,Hors Union Européenne,Non,0.0
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,2415.0,37852.0,36855.0,75105,Paris 5ème arrondissement,500.0,M,Française,Non,0.0
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,1225.0,0.0,0.0,75056,Paris,450.0,F,Française,Non,0.0
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,1535.0,14648.0,14688.0,75105,Paris 5ème arrondissement,700.0,F,Française,Non,0.0
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,924.0,0.0,0.0,75056,Paris,450.0,F,Française,Non,1.0

In [35]:
df['Code Géographique']=df['Code Géographique'].astype(str)
dfd['Code Géographique']=dfd['Code Géographique'].astype(int)

In [37]:
def code(commune):
    if commune>74999 and commune<=75999 :
        return 75056
    else :
        return commune


dfd['Code Géographique'] = dfd['Code Géographique'].apply(code)
dfd

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Ressources mensuelles du foyer,"RFR du foyer, année n-1","RFR du foyer, année n-2",Code Géographique,Commune logement souhaité,Montant maxi (loyer+charges) supportable,Sexe demandeur\n,Nationalité demandeur\n,Autre logement dé\ntenu demandeur\n,Nb de personnes handicapees
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,1499.0,NaN,NaN,75056,Paris,650.0,M,Hors Union Européenne,Non,0.0
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,1127.0,11932.0,10817.0,75056,Paris 5ème arrondissement,520.0,M,Française,Non,0.0
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,1501.0,NaN,NaN,75056,Paris,900.0,M,Hors Union Européenne,Non,0.0
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,674.0,0.0,NaN,75056,Paris 13ème arrondissement,800.0,F,Française,Non,0.0
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,3150.0,38081.0,NaN,75056,Paris 3ème arrondissement,1250.0,M,Française,Non,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,433.0,0.0,0.0,75056,Paris 1er arrondissement,350.0,M,Hors Union Européenne,Non,0.0
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,2415.0,37852.0,36855.0,75056,Paris 5ème arrondissement,500.0,M,Française,Non,0.0
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,1225.0,0.0,0.0,75056,Paris,450.0,F,Française,Non,0.0
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,1535.0,14648.0,14688.0,75056,Paris 5ème arrondissement,700.0,F,Française,Non,0.0
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,924.0,0.0,0.0,75056,Paris,450.0,F,Française,Non,1.0

In [38]:
df = pd.DataFrame(pd.read_excel(r'C:\Users\arceb\PycharmProjects\pythonProject/DGALN.xls'))
df

,Code Géographique,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques
0,01001,L'Abergement-Clémenciat,03
1,01002,L'Abergement-de-Varey,03
2,01004,Ambérieu-en-Bugey,03
3,01005,Ambérieux-en-Dombes,03
4,01006,Ambléon,03
...,...,...,...
36676,97613,M'Tsangamouji,02
36677,97614,Ouangani,02
36678,97615,Pamandzi,02
36679,97616,Sada,02
36680,97617,Tsingoni,02

In [39]:
df[df['Code Géographique']=='2A001']

,Code Géographique,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques
11155,2A001,Afa,02

In [44]:
df['Code Géographique']=df['Code Géographique'].astype(str)
dfd['Code Géographique']=dfd['Code Géographique'].astype(str)

In [45]:
base= dfd.merge(df, on='Code Géographique', how='inner')
base

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,"RFR du foyer, année n-2",Code Géographique,Commune logement souhaité,Montant maxi (loyer+charges) supportable,Sexe demandeur\n,Nationalité demandeur\n,Autre logement dé\ntenu demandeur\n,Nb de personnes handicapees,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,NaN,75056,Paris,650.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,10817.0,75056,Paris 5ème arrondissement,520.0,M,Française,Non,0.0,Paris,01 bis
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,NaN,75056,Paris,900.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,NaN,75056,Paris 13ème arrondissement,800.0,F,Française,Non,0.0,Paris,01 bis
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,NaN,75056,Paris 3ème arrondissement,1250.0,M,Française,Non,0.0,Paris,01 bis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,0.0,75056,Paris 1er arrondissement,350.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,36855.0,75056,Paris 5ème arrondissement,500.0,M,Française,Non,0.0,Paris,01 bis
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,0.0,75056,Paris,450.0,F,Française,Non,0.0,Paris,01 bis
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,14688.0,75056,Paris 5ème arrondissement,700.0,F,Française,Non,0.0,Paris,01 bis
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,0.0,75056,Paris,450.0,F,Française,Non,1.0,Paris,01 bis