In [1]:
import numpy as np
import pandas
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dfa = pd.read_csv(r'C:\Users\arceb\Desktop\Stage\BDD/attributaires_IDF.csv')
#dfd = pd.read_csv(r'C:\Users\arceb\Desktop\Stage\BDD/demandeurs_IDF(1).csv')

C:\Users\arceb\AppData\Local\Temp\ipykernel_29652\549424720.py:1: DtypeWarning: Columns (7,8,25) have mixed types. Specify dtype option on import or set low_memory=False.
  dfa = pd.read_csv(r'C:\Users\arceb\Desktop\Stage\BDD/attributaires_IDF.csv')

In [4]:
dfa

,Unnamed: 0,région,Numéro Unique,Date création demande,Date de la radiation,Age demandeur,Situation familiale,Code département logement actuel,Code INSEE logt actuel,Commune logt actuel,...,Code de la commune attribuée,Région du logement attribué,Type du logement attribué,Est en QPV,Surface du logement attribué,Statut DALO,Date de la décision DALO\n\n,Accompagnement social,Diagnostic social,Réservataire
0,0,Ile-de-France,175037900427000002,1979-03-01 00:00:00,2018-04-13 00:00:00,59,Veuf (ve),75,75112.0,Paris 12ème arrondissement,...,75120,Ile-de-France,T1,Oui,20,Actif relogé,2012-06-15 00:00:00,Non,Non,"Contingent des collectivités territoriales, de..."
1,1,Ile-de-France,175118000728300002,1980-11-14 00:00:00,2018-06-04 00:00:00,72,Veuf (ve),75,75117.0,Paris 17ème arrondissement,...,75117,Ile-de-France,T2,Non,44,Actif relogé,2013-07-12 00:00:00,Non,Non,Contingent autres réservataires
2,2,Ile-de-France,211048217550092024,1982-04-01 00:00:00,2018-11-27 00:00:00,91,Divorcé (e),92,92024.0,Clichy,...,92024,Ile-de-France,T1,Non,35,Non renseigné,NaN,Non,Non,"Contingent des collectivités territoriales, de..."
3,3,Ile-de-France,175108301617300002,1983-10-17 00:00:00,2018-10-30 00:00:00,64,Célibataire,75,75111.0,Paris 11ème arrondissement,...,75119,Ile-de-France,T2,Non,55,Non renseigné,NaN,Non,Non,Hors contingent
4,4,Ile-de-France,175128420982700002,1984-12-01 00:00:00,2018-04-10 00:00:00,57,Célibataire,75,75119.0,Paris 19ème arrondissement,...,75120,Ile-de-France,T2,Non,53,Non renseigné,NaN,Non,Non,"Contingent des collectivités territoriales, de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,153709,Ile-de-France,1111218129847GDPUB,2018-12-19 00:00:00,2019-01-01 00:00:00,70,Marié (e),78,78440.0,Les Mureaux,...,78361,Ile-de-France,T2,Oui,47,Non renseigné,NaN,Non,Non,Contingent autres réservataires
153710,153710,Ile-de-France,111121812788778498,2018-12-20 00:00:00,2018-12-21 00:00:00,51,Célibataire,78,78498.0,Poissy,...,78498,Ile-de-France,T2,Oui,46,Non renseigné,NaN,Non,Non,Contingent commune
153711,153711,Ile-de-France,111121812792310122,2018-12-20 00:00:00,2018-12-28 00:00:00,86,Veuf (ve),78,78440.0,Les Mureaux,...,78314,Ile-de-France,T2,Non,53,Non renseigné,NaN,Non,Non,Hors contingent
153712,153712,Ile-de-France,111121813038177438,2018-12-21 00:00:00,2018-12-31 00:00:00,48,Concubin (e),77,77438.0,Saint-Thibault-des-Vignes,...,77243,Ile-de-France,T3,Non,63,Non renseigné,NaN,Non,Non,Contingent département
153713,153713,Ile-de-France,111121813209910389,2018-12-28 00:00:00,2018-12-31 00:00:00,28,Concubin (e),91,91228.0,Évry,...,91174,Ile-de-France,T2,Oui,50,Non renseigné,NaN,Non,Non,Contingent préfet prioritaires (hors fonctionn...

In [5]:
dfa[dfa['Montant loyer mensuel du logement attribué\n']==0].count()

Unnamed: 0                                      10051
région                                          10051
Numéro Unique                                   10051
Date création demande                           10051
Date de la radiation                            10051
Age demandeur                                   10051
Situation familiale                             10051
Code département logement actuel                10051
Code INSEE logt actuel                          10045
Commune logt actuel                             10045
SIRET de l'EPCI (logement du demandeur)         10045
Nom de l'EPCI (logement du demandeur)           10045
Mode de logement actuel                         10051
Type de logement actuel                         10051
Nb résidents                                     9316
Loyer montant mensuel                            8571
Montant AL / APL                                 7109
Composition foyer demandeur                     10051
Situation professionnelle demandeur             10051
motif n°1 de la demande                         10051
Nb unités de consommation du foyer              10051
Ressources mensuelles du foyer                   9954
RFR du foyer, année n-1                          4088
RFR du foyer, année n-2                          8586
Montant maxi (loyer+charges) supportable         8883
Numéro RPLS du logement attribué                 9934
Montant loyer mensuel du logement attribué\n    10051
SIRET de l'EPCI du logement attribué            10051
Nom de l'EPCI du logement attribué              10051
Code de la commune attribuée                    10051
Région du logement attribué                     10051
Type du logement attribué                       10051
Est en QPV                                      10051
Surface du logement attribué                    10051
Statut DALO                                     10051
Date de la décision DALO\n\n                     1773
Accompagnement social                           10051
Diagnostic social                               10051
Réservataire                                    10051
dtype: int64

In [6]:
base=dfa[[ "Montant maxi (loyer+charges) supportable",  "Ressources mensuelles du foyer", "Nb unités de consommation du foyer", "Loyer montant mensuel", "Composition foyer demandeur",  "Montant loyer mensuel du logement attribué\n", "Numéro Unique"]]

In [7]:
base.dropna()

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002
...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389

In [8]:
def plafond_loyer(compo_foyer):
    if compo_foyer=="Personne seule":
        return 295.05
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 355.85
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 402.18
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 402.18+58.34
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 402.18+58.34+58.34
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 402.18+58.34+58.34+58.34
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 402.18+58.34+58.34+58.34+58.34
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 402.18+58.34+58.34+58.34+58.34+58.34

In [14]:
base['Plafond loyer'] = base['Composition foyer demandeur'].apply(plafond_loyer)

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\2556208101.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Plafond loyer'] = base['Composition foyer demandeur'].apply(plafond_loyer)

In [15]:
base

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05
...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18

In [19]:
base['Loyer éligible']=base[['Montant loyer mensuel du logement attribué\n','Plafond loyer']].min(axis=1)

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3744413431.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Loyer éligible']=base[['Montant loyer mensuel du logement attribué\n','Plafond loyer']].min(axis=1)

In [20]:
base

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05
...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18

In [21]:
def charges(compo_foyer):
    if compo_foyer=="Personne seule":
        return 53.67
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 53.67
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 53.67+12.16
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 53.67+12.16+12.16
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 53.67+12.16+12.16+12.16
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 53.67+12.16+12.16+12.16+12.16
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 53.67+12.16+12.16+12.16+12.16+12.16
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 53.67+12.16+12.16+12.16+12.16+12.16+12.16

In [22]:
base['Montant forfaitaire au titre des charges'] = base['Composition foyer demandeur'].apply(charges)
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3530984206.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Montant forfaitaire au titre des charges'] = base['Composition foyer demandeur'].apply(charges)

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67
...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83

In [24]:
base["Revenu imposable"]=(base['Ressources mensuelles du foyer']*0.9)*12
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\2188573719.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base["Revenu imposable"]=(base['Ressources mensuelles du foyer']*0.9)*12

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,Revenu imposable
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,6004.8
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,19040.4
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,13834.8
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,38178.0
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,33955.2
...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,14526.0
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,10692.0
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,19407.6
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,37627.2
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,24915.6

In [25]:
def abattement(compo_foyer):
    if compo_foyer=="Personne seule":
        return 4562
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 6534
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 7793
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 7969
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 8274
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 8581
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 8886
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 9192

In [26]:
base['Abattement forfaitaire appliqué aux ressources du ménage '] = base['Composition foyer demandeur'].apply(abattement)
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3792081555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Abattement forfaitaire appliqué aux ressources du ménage '] = base['Composition foyer demandeur'].apply(abattement)

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,Revenu imposable,Abattement forfaitaire appliqué aux ressources du ménage
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,6004.8,4562
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,19040.4,4562
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,13834.8,4562
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,38178.0,6534
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,33955.2,4562
...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,14526.0,6534
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,10692.0,4562
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,19407.6,4562
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,37627.2,7969
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,24915.6,7793

In [39]:
base['Participation minimale']=(base['Loyer éligible']+base['Montant forfaitaire au titre des charges'])*.085

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\662227790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Participation minimale']=(base['Loyer éligible']+base['Montant forfaitaire au titre des charges'])*.085

In [40]:
base['35.02']=35.02

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\684511327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['35.02']=35.02

In [41]:
base['Participation minimale']=base[['Participation minimale','35.02']].max(axis=1)

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\1837699471.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Participation minimale']=base[['Participation minimale','35.02']].max(axis=1)

In [42]:
base

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,Revenu imposable,Abattement forfaitaire appliqué aux ressources du ménage,Rp,35.02,Participation minimale
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,6004.8,4562,35.02000,35.02,35.02000
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,19040.4,4562,35.02000,35.02,35.02000
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,13834.8,4562,35.02000,35.02,35.02000
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,38178.0,6534,35.02000,35.02,35.02000
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,33955.2,4562,35.02000,35.02,35.02000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,14526.0,6534,35.02000,35.02,35.02000
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,10692.0,4562,35.02000,35.02,35.02000
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,19407.6,4562,35.02000,35.02,35.02000
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,37627.2,7969,35.95415,35.02,35.95415
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,24915.6,7793,39.78085,35.02,39.78085

In [43]:
base['0']=0
base["Rp"]=base['Revenu imposable']-base['Abattement forfaitaire appliqué aux ressources du ménage ']
base["Rp"]=base[['Rp','0']].max(axis=1)
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3219225509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['0']=0
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3219225509.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base["Rp"]=base['Revenu imposable']-base['Abattement forfaitaire appliqué aux ressources du ménage ']
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3219225509.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base["Rp"]=base[['Rp','0']].max(axis=1)

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,Revenu imposable,Abattement forfaitaire appliqué aux ressources du ménage,Rp,35.02,Participation minimale,0
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,6004.8,4562,1442.8,35.02,35.02000,0
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,19040.4,4562,14478.4,35.02,35.02000,0
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,13834.8,4562,9272.8,35.02,35.02000,0
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,38178.0,6534,31644.0,35.02,35.02000,0
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,33955.2,4562,29393.2,35.02,35.02000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,14526.0,6534,7992.0,35.02,35.02000,0
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,10692.0,4562,6130.0,35.02,35.02000,0
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,19407.6,4562,14845.6,35.02,35.02000,0
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,37627.2,7969,29658.2,35.02,35.95415,0
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,24915.6,7793,17122.6,35.02,39.78085,0

In [44]:
def tf(compo_foyer):
    if compo_foyer=="Personne seule":
        return 0.0283
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 0.0315
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 0.0270
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 0.0238
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 0.0201
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 0.0185
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 0.0185-0.0006
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 0.0185-0.0006-0.0006

In [45]:
base['Taux fonction de la taille de la famille'] = base['Composition foyer demandeur'].apply(tf)
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\2851108637.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Taux fonction de la taille de la famille'] = base['Composition foyer demandeur'].apply(tf)

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,Revenu imposable,Abattement forfaitaire appliqué aux ressources du ménage,Rp,35.02,Participation minimale,0,Taux fonction de la taille de la famille
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,6004.8,4562,1442.8,35.02,35.02000,0,0.0283
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,19040.4,4562,14478.4,35.02,35.02000,0,0.0283
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,13834.8,4562,9272.8,35.02,35.02000,0,0.0283
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,38178.0,6534,31644.0,35.02,35.02000,0,0.0315
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,33955.2,4562,29393.2,35.02,35.02000,0,0.0283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,14526.0,6534,7992.0,35.02,35.02000,0,0.0315
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,10692.0,4562,6130.0,35.02,35.02000,0,0.0283
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,19407.6,4562,14845.6,35.02,35.02000,0,0.0283
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,37627.2,7969,29658.2,35.02,35.95415,0,0.0238
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,24915.6,7793,17122.6,35.02,39.78085,0,0.0270

In [46]:
def lr(compo_foyer):
    if compo_foyer=="Personne seule":
        return 257.14
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 314.74
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 354.17
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 354.17+51.54
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 354.17+51.54+51.54
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 17+51.54+51.54+51.54
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 354.17+51.54+51.54+51.54+51.54
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 354.17+51.54+51.54+51.54+51.54+51.54

In [47]:
base['Loyer de référence'] = base['Composition foyer demandeur'].apply(lr)
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\2069521994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Loyer de référence'] = base['Composition foyer demandeur'].apply(lr)

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,Revenu imposable,Abattement forfaitaire appliqué aux ressources du ménage,Rp,35.02,Participation minimale,0,Taux fonction de la taille de la famille,Loyer de référence
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,6004.8,4562,1442.8,35.02,35.02000,0,0.0283,257.14
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,19040.4,4562,14478.4,35.02,35.02000,0,0.0283,257.14
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,13834.8,4562,9272.8,35.02,35.02000,0,0.0283,257.14
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,38178.0,6534,31644.0,35.02,35.02000,0,0.0315,314.74
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,33955.2,4562,29393.2,35.02,35.02000,0,0.0283,257.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,14526.0,6534,7992.0,35.02,35.02000,0,0.0315,314.74
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,10692.0,4562,6130.0,35.02,35.02000,0,0.0283,257.14
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,19407.6,4562,14845.6,35.02,35.02000,0,0.0283,257.14
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,37627.2,7969,29658.2,35.02,35.95415,0,0.0238,405.71
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,24915.6,7793,17122.6,35.02,39.78085,0,0.0270,354.17

In [48]:
base['Rapport RL']=base['Loyer éligible']/base['Loyer de référence']
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\2579458656.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Rapport RL']=base['Loyer éligible']/base['Loyer de référence']

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,Revenu imposable,Abattement forfaitaire appliqué aux ressources du ménage,Rp,35.02,Participation minimale,0,Taux fonction de la taille de la famille,Loyer de référence,Rapport RL
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,6004.8,4562,1442.8,35.02,35.02000,0,0.0283,257.14,0.000000
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,19040.4,4562,14478.4,35.02,35.02000,0,0.0283,257.14,1.147429
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,13834.8,4562,9272.8,35.02,35.02000,0,0.0283,257.14,1.147429
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,38178.0,6534,31644.0,35.02,35.02000,0,0.0315,314.74,1.130616
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,33955.2,4562,29393.2,35.02,35.02000,0,0.0283,257.14,1.147429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,14526.0,6534,7992.0,35.02,35.02000,0,0.0315,314.74,0.861028
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,10692.0,4562,6130.0,35.02,35.02000,0,0.0283,257.14,1.022789
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,19407.6,4562,14845.6,35.02,35.02000,0,0.0283,257.14,1.147429
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,37627.2,7969,29658.2,35.02,35.95415,0,0.0238,405.71,0.850361
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,24915.6,7793,17122.6,35.02,39.78085,0,0.0270,354.17,1.135556

In [52]:
base['C1']=0

def c1(rl):
    if rl>0.75:
        return 0.3
    else:
        return 0

base['C1'] = base['Rapport RL'].apply(c1)
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\285368886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['C1']=0
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\285368886.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['C1'] = base['Rapport RL'].apply(c1)

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,Revenu imposable,Abattement forfaitaire appliqué aux ressources du ménage,Rp,35.02,Participation minimale,0,Taux fonction de la taille de la famille,Loyer de référence,Rapport RL,C1
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,6004.8,4562,1442.8,35.02,35.02000,0,0.0283,257.14,0.000000,0.0
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,19040.4,4562,14478.4,35.02,35.02000,0,0.0283,257.14,1.147429,0.3
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,13834.8,4562,9272.8,35.02,35.02000,0,0.0283,257.14,1.147429,0.3
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,38178.0,6534,31644.0,35.02,35.02000,0,0.0315,314.74,1.130616,0.3
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,33955.2,4562,29393.2,35.02,35.02000,0,0.0283,257.14,1.147429,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,14526.0,6534,7992.0,35.02,35.02000,0,0.0315,314.74,0.861028,0.3
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,10692.0,4562,6130.0,35.02,35.02000,0,0.0283,257.14,1.022789,0.3
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,19407.6,4562,14845.6,35.02,35.02000,0,0.0283,257.14,1.147429,0.3
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,37627.2,7969,29658.2,35.02,35.95415,0,0.0238,405.71,0.850361,0.3
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,24915.6,7793,17122.6,35.02,39.78085,0,0.0270,354.17,1.135556,0.3

In [54]:
base['C2']=0

def c2(rl):
    if rl>0.45 and rl<=0.75 :
        return 0.0045
    elif rl>0.75:
        return 0.0068
    else:
        return 0

base['C2'] = base['Rapport RL'].apply(c2)
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\1269860709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['C2']=0
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\1269860709.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['C2'] = base['Rapport RL'].apply(c2)

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,...,Abattement forfaitaire appliqué aux ressources du ménage,Rp,35.02,Participation minimale,0,Taux fonction de la taille de la famille,Loyer de référence,Rapport RL,C1,C2
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,...,4562,1442.8,35.02,35.02000,0,0.0283,257.14,0.000000,0.0,0.0000
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,...,4562,14478.4,35.02,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,...,4562,9272.8,35.02,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,...,6534,31644.0,35.02,35.02000,0,0.0315,314.74,1.130616,0.3,0.0068
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,...,4562,29393.2,35.02,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,...,6534,7992.0,35.02,35.02000,0,0.0315,314.74,0.861028,0.3,0.0068
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,...,4562,6130.0,35.02,35.02000,0,0.0283,257.14,1.022789,0.3,0.0068
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,...,4562,14845.6,35.02,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,...,7969,29658.2,35.02,35.95415,0,0.0238,405.71,0.850361,0.3,0.0068
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,...,7793,17122.6,35.02,39.78085,0,0.0270,354.17,1.135556,0.3,0.0068

In [55]:
base['C3']=0

def c3(rl):
    if rl>0.45 and rl<=0.75 :
        return 0.45
    elif rl>0.75:
        return 0.75
    else:
        return 0

base['C3'] = base['Rapport RL'].apply(c3)
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\2196040518.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['C3']=0
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\2196040518.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['C3'] = base['Rapport RL'].apply(c3)

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,...,Rp,35.02,Participation minimale,0,Taux fonction de la taille de la famille,Loyer de référence,Rapport RL,C1,C2,C3
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,...,1442.8,35.02,35.02000,0,0.0283,257.14,0.000000,0.0,0.0000,0.00
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,...,14478.4,35.02,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068,0.75
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,...,9272.8,35.02,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068,0.75
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,...,31644.0,35.02,35.02000,0,0.0315,314.74,1.130616,0.3,0.0068,0.75
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,...,29393.2,35.02,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,...,7992.0,35.02,35.02000,0,0.0315,314.74,0.861028,0.3,0.0068,0.75
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,...,6130.0,35.02,35.02000,0,0.0283,257.14,1.022789,0.3,0.0068,0.75
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,...,14845.6,35.02,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068,0.75
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,...,29658.2,35.02,35.95415,0,0.0238,405.71,0.850361,0.3,0.0068,0.75
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,...,17122.6,35.02,39.78085,0,0.0270,354.17,1.135556,0.3,0.0068,0.75

In [57]:
base['TL']=base['Rapport RL']-base['C3']
base['TL']= base['C2']*base['TL']
base['TL']= 0.0045*base['C1'] + base['TL']

#TL=0.0045*C1+C2*(RL-C3)

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3216224358.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['TL']=base['Rapport RL']-base['C3']
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3216224358.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['TL']= base['C2']*base['TL']
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3216224358.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['TL']= 0.0045*base['C1'] + base['TL']

In [60]:
base

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,...,Participation minimale,0,Taux fonction de la taille de la famille,Loyer de référence,Rapport RL,C1,C2,C3,TL,Taux de prise en compte des ressources des ménages (Tp)
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,...,35.02000,0,0.0283,257.14,0.000000,0.0,0.0000,0.00,0.000000,0.028300
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,...,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,...,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,...,35.02000,0,0.0315,314.74,1.130616,0.3,0.0068,0.75,0.003938,0.035438
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,...,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,...,35.02000,0,0.0315,314.74,0.861028,0.3,0.0068,0.75,0.002105,0.033605
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,...,35.02000,0,0.0283,257.14,1.022789,0.3,0.0068,0.75,0.003205,0.031505
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,...,35.02000,0,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,...,35.95415,0,0.0238,405.71,0.850361,0.3,0.0068,0.75,0.002032,0.025832
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,...,39.78085,0,0.0270,354.17,1.135556,0.3,0.0068,0.75,0.003972,0.030972

In [67]:
base['Taux de prise en compte des ressources des ménages (Tp)']=base['TL']+ base['Taux fonction de la taille de la famille']

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\300639711.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Participation personnelle du ménage']=base['Taux de prise en compte des ressources des ménages (Tp)']*base['Rp']
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\300639711.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['Participation personnelle du ménage']=base['Participation personnelle du ménage'] + base['Participation minimale']

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,...,Taux fonction de la taille de la famille,Loyer de référence,Rapport RL,C1,C2,C3,TL,Taux de prise en compte des ressources des ménages (Tp),Participation personnelle du ménage,APL
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,...,0.0283,257.14,0.000000,0.0,0.0000,0.00,0.000000,0.028300,75.851240,-22.181240
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,...,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,503.432726,-154.712726
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,...,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,335.018448,13.701552
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,...,0.0315,314.74,1.130616,0.3,0.0068,0.75,0.003938,0.035438,1156.425992,-746.905992
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,...,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,985.964092,-637.244092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,...,0.0315,314.74,0.861028,0.3,0.0068,0.75,0.002105,0.033605,303.591091,21.078909
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,...,0.0283,257.14,1.022789,0.3,0.0068,0.75,0.003205,0.031505,228.145443,88.524557
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,...,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,515.312571,-166.592571
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,...,0.0238,405.71,0.850361,0.3,0.0068,0.75,0.002032,0.025832,802.098280,-379.108280
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,...,0.0270,354.17,1.135556,0.3,0.0068,0.75,0.003972,0.030972,570.098307,-102.088307

In [65]:
base['Participation personnelle du ménage']=base['Taux de prise en compte des ressources des ménages (Tp)']*base['Rp']
base['Participation personnelle du ménage']=base['Participation personnelle du ménage'] + base['Participation minimale']
base

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3801738382.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['APL']=base['Loyer éligible'] + base['Montant forfaitaire au titre des charges']-base['Participation personnelle du ménage']

In [68]:
base['APL']=base['Loyer éligible'] + base['Montant forfaitaire au titre des charges']-base['Participation personnelle du ménage']

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3801738382.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['APL']=base['Loyer éligible'] + base['Montant forfaitaire au titre des charges']-base['Participation personnelle du ménage']

In [69]:
base['P1']=3.4*base['Montant loyer mensuel du logement attribué\n']
base['P2']=4*base['Montant loyer mensuel du logement attribué\n']

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\679197961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['P1']=3.4*base['Montant loyer mensuel du logement attribué\n']
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\679197961.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['P2']=4*base['Montant loyer mensuel du logement attribué\n']

In [71]:
base['APL1']=(base['P2']*base['Montant loyer mensuel du logement attribué\n']-base['Loyer éligible'])/((base['P2']-base['P1'])*base['Montant loyer mensuel du logement attribué\n'])*base['APL']
#replace APL=(P2*Lp-L)/((P2-P1)*Lp)*APL if L>P1 & L<=P2

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\837855797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['APL1']=(base['P2']*base['Montant loyer mensuel du logement attribué\n']-base['Loyer éligible'])/((base['P2']-base['P1'])*base['Montant loyer mensuel du logement attribué\n'])*base['APL']

In [79]:
base

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,...,C1,C2,C3,TL,Taux de prise en compte des ressources des ménages (Tp),Participation personnelle du ménage,APL,P1,P2,APL1
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,...,0.0,0.0000,0.00,0.000000,0.028300,75.851240,-22.181240,0.0,0,NaN
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,503.432726,-154.712726,1013.2,1192,-1030.561455
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,335.018448,13.701552,1264.8,1488,91.294993
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,...,0.3,0.0068,0.75,0.003938,0.035438,1156.425992,-746.905992,2754.0,3240,-4978.698111
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,985.964092,-637.244092,2128.4,2504,-4247.494292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,...,0.3,0.0068,0.75,0.002105,0.033605,303.591091,21.078909,921.4,1084,140.396420
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,...,0.3,0.0068,0.75,0.003205,0.031505,228.145443,88.524557,894.2,1052,589.602724
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,515.312571,-166.592571,1604.8,1888,-1110.249423
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,...,0.3,0.0068,0.75,0.002032,0.025832,802.098280,-379.108280,1173.0,1380,-2525.557094
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,...,0.3,0.0068,0.75,0.003972,0.030972,570.098307,-102.088307,1485.8,1748,-680.230385

In [87]:
base1=base.dropna()
base1 = base1.reset_index(drop=True)
base1

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,...,C1,C2,C3,TL,Taux de prise en compte des ressources des ménages (Tp),Participation personnelle du ménage,APL,P1,P2,APL1
0,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,503.432726,-154.712726,1013.2,1192,-1030.561455
1,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,335.018448,13.701552,1264.8,1488,91.294993
2,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,...,0.3,0.0068,0.75,0.003938,0.035438,1156.425992,-746.905992,2754.0,3240,-4978.698111
3,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,985.964092,-637.244092,2128.4,2504,-4247.494292
4,0.0,1819.0,1.0,679.0,Personne seule,441,175018604471600002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,522.999530,-174.279530,1499.4,1764,-1161.422864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113706,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,...,0.3,0.0068,0.75,0.002105,0.033605,303.591091,21.078909,921.4,1084,140.396420
113707,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,...,0.3,0.0068,0.75,0.003205,0.031505,228.145443,88.524557,894.2,1052,589.602724
113708,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,515.312571,-166.592571,1604.8,1888,-1110.249423
113709,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,...,0.3,0.0068,0.75,0.002032,0.025832,802.098280,-379.108280,1173.0,1380,-2525.557094
113710,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,...,0.3,0.0068,0.75,0.003972,0.030972,570.098307,-102.088307,1485.8,1748,-680.230385

In [89]:
base1.rename(columns={'Montant loyer mensuel du logement attribué\n': 'Montant loyer mensuel du logement attribue'}, inplace=True)

In [90]:
def apl(l):
    if l>base1[base1['P1']] and l<=base1[base1['P2']] :
        return base1['APL1']
    elif l>base1[base1['P2'] * base1['Montant loyer mensuel du logement attribue']]:
        return 0
    else:
        return 0

base1['APL'] = base1['Montant loyer mensuel du logement attribue'].apply(apl)
base1

KeyError: "None of [Float64Index([1013.1999999999999,             1264.8,             2754.0,\n                          2128.4, 1499.3999999999999, 2369.7999999999997,\n              2216.7999999999997, 1414.3999999999999,             2631.6,\n                          3070.2,\n              ...\n                          2142.0,            33996.6,             1003.0,\n                          2400.4,             2713.2,              921.4,\n               894.1999999999999,             1604.8,             1173.0,\n                          1485.8],\n             dtype='float64', length=113711)] are in the [columns]"

In [82]:
#replace APL=(P2*Lp-L)/((P2-P1)*Lp)*APL if L>P1 & L<=P2
def apl(l):
    if base[l] > base[base['P1']] and l <= base[base['P2']]:
        return base['APL1']
    elif base[l] > base[base['P2'] * base['Montant loyer mensuel du logement attribué\n']]:
        return 0
    else:
        return 0


base['APL'] = base['Montant loyer mensuel du logement attribué\n'].apply(apl)
base

KeyError: 0

In [ ]:
#replace APL=(P2*Lp-L)/((P2-P1)*Lp)*APL if L>P1 & L<=P2
def apl(l):
    if l > base[base['P1']] and l <= base[base['P2']]:
        return base['APL1']
    elif l > base[base['P2'] * base['Montant loyer mensuel du logement attribué\n']]:
        return 0
    else:
        return 0


base['APL'] = base['Montant loyer mensuel du logement attribué\n'].apply(apl)
base