In [1]:
import numpy as np
import pandas
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'C:\Users\arceb\PycharmProjects\pythonProject/Paris_final.csv', index_col = 0)

C:\Users\arceb\AppData\Local\Temp\ipykernel_17280\1945794923.py:1: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\arceb\PycharmProjects\pythonProject/Paris_final.csv', index_col = 0)

In [3]:
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,"RFR du foyer, année n-2",Code Géographique,Commune logement souhaité,Montant maxi (loyer+charges) supportable,Sexe demandeur\n,Nationalité demandeur\n,Autre logement dé\ntenu demandeur\n,Nb de personnes handicapees,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,NaN,75056,Paris,650.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,10817.0,75056,Paris 5ème arrondissement,520.0,M,Française,Non,0.0,Paris,01 bis
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,NaN,75056,Paris,900.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,NaN,75056,Paris 13ème arrondissement,800.0,F,Française,Non,0.0,Paris,01 bis
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,NaN,75056,Paris 3ème arrondissement,1250.0,M,Française,Non,0.0,Paris,01 bis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,0.0,75056,Paris 1er arrondissement,350.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,36855.0,75056,Paris 5ème arrondissement,500.0,M,Française,Non,0.0,Paris,01 bis
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,0.0,75056,Paris,450.0,F,Française,Non,0.0,Paris,01 bis
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,14688.0,75056,Paris 5ème arrondissement,700.0,F,Française,Non,0.0,Paris,01 bis
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,0.0,75056,Paris,450.0,F,Française,Non,1.0,Paris,01 bis

In [4]:
def plafond_loyer(compo_foyer):
    if compo_foyer=="Personne seule":
        return 295.05
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 355.85
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 402.18
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 402.18+58.34
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 402.18+58.34+58.34
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 402.18+58.34+58.34+58.34
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 402.18+58.34+58.34+58.34+58.34
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 402.18+58.34+58.34+58.34+58.34+58.34

In [5]:
df['PL'] = df['Composition foyer demandeur'].apply(plafond_loyer)

In [6]:
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Code Géographique,Commune logement souhaité,Montant maxi (loyer+charges) supportable,Sexe demandeur\n,Nationalité demandeur\n,Autre logement dé\ntenu demandeur\n,Nb de personnes handicapees,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques,PL
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,75056,Paris,650.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,460.52
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,75056,Paris 5ème arrondissement,520.0,M,Française,Non,0.0,Paris,01 bis,295.05
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,75056,Paris,900.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,577.20
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,75056,Paris 13ème arrondissement,800.0,F,Française,Non,0.0,Paris,01 bis,402.18
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,75056,Paris 3ème arrondissement,1250.0,M,Française,Non,0.0,Paris,01 bis,355.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,75056,Paris 1er arrondissement,350.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,295.05
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,75056,Paris 5ème arrondissement,500.0,M,Française,Non,0.0,Paris,01 bis,460.52
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,75056,Paris,450.0,F,Française,Non,0.0,Paris,01 bis,295.05
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,75056,Paris 5ème arrondissement,700.0,F,Française,Non,0.0,Paris,01 bis,295.05
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,75056,Paris,450.0,F,Française,Non,1.0,Paris,01 bis,295.05

In [7]:
df['L']=df[['Loyer montant mensuel','PL']].min(axis=1)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Commune logement souhaité,Montant maxi (loyer+charges) supportable,Sexe demandeur\n,Nationalité demandeur\n,Autre logement dé\ntenu demandeur\n,Nb de personnes handicapees,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques,PL,L
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,Paris,650.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,460.52,460.52
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,Paris 5ème arrondissement,520.0,M,Française,Non,0.0,Paris,01 bis,295.05,295.05
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,Paris,900.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,577.20,577.20
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,Paris 13ème arrondissement,800.0,F,Française,Non,0.0,Paris,01 bis,402.18,402.18
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,Paris 3ème arrondissement,1250.0,M,Française,Non,0.0,Paris,01 bis,355.85,355.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,Paris 1er arrondissement,350.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,295.05,295.05
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,Paris 5ème arrondissement,500.0,M,Française,Non,0.0,Paris,01 bis,460.52,307.00
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,Paris,450.0,F,Française,Non,0.0,Paris,01 bis,295.05,295.05
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,Paris 5ème arrondissement,700.0,F,Française,Non,0.0,Paris,01 bis,295.05,295.05
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,Paris,450.0,F,Française,Non,1.0,Paris,01 bis,295.05,295.05

In [8]:
def charges(compo_foyer):
    if compo_foyer=="Personne seule":
        return 53.67
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 53.67
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 53.67+12.16
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 53.67+12.16+12.16
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 53.67+12.16+12.16+12.16
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 53.67+12.16+12.16+12.16+12.16
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 53.67+12.16+12.16+12.16+12.16+12.16
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 53.67+12.16+12.16+12.16+12.16+12.16+12.16

In [9]:
df['C'] = df['Composition foyer demandeur'].apply(charges)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Montant maxi (loyer+charges) supportable,Sexe demandeur\n,Nationalité demandeur\n,Autre logement dé\ntenu demandeur\n,Nb de personnes handicapees,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques,PL,L,C
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,650.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,460.52,460.52,77.99
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,520.0,M,Française,Non,0.0,Paris,01 bis,295.05,295.05,53.67
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,900.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,577.20,577.20,102.31
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,800.0,F,Française,Non,0.0,Paris,01 bis,402.18,402.18,65.83
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,1250.0,M,Française,Non,0.0,Paris,01 bis,355.85,355.85,53.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,350.0,M,Hors Union Européenne,Non,0.0,Paris,01 bis,295.05,295.05,53.67
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,500.0,M,Française,Non,0.0,Paris,01 bis,460.52,307.00,77.99
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,450.0,F,Française,Non,0.0,Paris,01 bis,295.05,295.05,53.67
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,700.0,F,Française,Non,0.0,Paris,01 bis,295.05,295.05,53.67
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,450.0,F,Française,Non,1.0,Paris,01 bis,295.05,295.05,53.67

In [10]:
df['P1']=3.4
df['P2']=4.0

In [11]:
df["R"]=(df['Ressources imposables mensuelles moyennes (RI)']*0.9)*12
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Autre logement dé\ntenu demandeur\n,Nb de personnes handicapees,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques,PL,L,C,P1,P2,R
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,Non,0.0,Paris,01 bis,460.52,460.52,77.99,3.4,4.0,1134.0
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,Non,0.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,12171.6
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,Non,0.0,Paris,01 bis,577.20,577.20,102.31,3.4,4.0,0.0
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,Non,0.0,Paris,01 bis,402.18,402.18,65.83,3.4,4.0,0.0
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,Non,0.0,Paris,01 bis,355.85,355.85,53.67,3.4,4.0,15228.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,Non,0.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,0.0
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,Non,0.0,Paris,01 bis,460.52,307.00,77.99,3.4,4.0,26082.0
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,Non,0.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,8812.8
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,Non,0.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,16578.0
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,Non,1.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,0.0

In [12]:
def abattement(compo_foyer):
    if compo_foyer=="Personne seule":
        return 4562
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 6534
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 7793
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 7969
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 8274
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 8581
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 8886
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 9192

In [13]:
df['R0'] = df['Composition foyer demandeur'].apply(abattement)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Nb de personnes handicapees,Libellé de la commune,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques,PL,L,C,P1,P2,R,R0
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,0.0,Paris,01 bis,460.52,460.52,77.99,3.4,4.0,1134.0,7969
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,0.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,12171.6,4562
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,0.0,Paris,01 bis,577.20,577.20,102.31,3.4,4.0,0.0,8581
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,0.0,Paris,01 bis,402.18,402.18,65.83,3.4,4.0,0.0,7793
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,0.0,Paris,01 bis,355.85,355.85,53.67,3.4,4.0,15228.0,6534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,0.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,0.0,4562
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,0.0,Paris,01 bis,460.52,307.00,77.99,3.4,4.0,26082.0,7969
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,0.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,8812.8,4562
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,0.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,16578.0,4562
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,1.0,Paris,01 bis,295.05,295.05,53.67,3.4,4.0,0.0,4562

In [14]:
df['P0']=(df['L']+df['C'])*.085

In [15]:
df['35.02']=35.02

In [16]:
df['P0']=df[['P0','35.02']].max(axis=1)

In [17]:
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Zonage I/II/III\nArrêté du 17 mars 1978 relatif au classement des communes par zones geographiques,PL,L,C,P1,P2,R,R0,P0,35.02
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,01 bis,460.52,460.52,77.99,3.4,4.0,1134.0,7969,45.77335,35.02
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,01 bis,295.05,295.05,53.67,3.4,4.0,12171.6,4562,35.02000,35.02
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,01 bis,577.20,577.20,102.31,3.4,4.0,0.0,8581,57.75835,35.02
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,01 bis,402.18,402.18,65.83,3.4,4.0,0.0,7793,39.78085,35.02
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,01 bis,355.85,355.85,53.67,3.4,4.0,15228.0,6534,35.02000,35.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,01 bis,295.05,295.05,53.67,3.4,4.0,0.0,4562,35.02000,35.02
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,01 bis,460.52,307.00,77.99,3.4,4.0,26082.0,7969,35.02000,35.02
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,01 bis,295.05,295.05,53.67,3.4,4.0,8812.8,4562,35.02000,35.02
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,01 bis,295.05,295.05,53.67,3.4,4.0,16578.0,4562,35.02000,35.02
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,01 bis,295.05,295.05,53.67,3.4,4.0,0.0,4562,35.02000,35.02

In [18]:
df['0']=0
df["Rp"]=df['Ressources imposables mensuelles moyennes (RI)']-df['C']
df["Rp"]=df[['Rp','0']].max(axis=1)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,L,C,P1,P2,R,R0,P0,35.02,0,Rp
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,460.52,77.99,3.4,4.0,1134.0,7969,45.77335,35.02,0,27.01
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,295.05,53.67,3.4,4.0,12171.6,4562,35.02000,35.02,0,1073.33
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,577.20,102.31,3.4,4.0,0.0,8581,57.75835,35.02,0,0.00
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,402.18,65.83,3.4,4.0,0.0,7793,39.78085,35.02,0,0.00
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,355.85,53.67,3.4,4.0,15228.0,6534,35.02000,35.02,0,1356.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,295.05,53.67,3.4,4.0,0.0,4562,35.02000,35.02,0,0.00
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,307.00,77.99,3.4,4.0,26082.0,7969,35.02000,35.02,0,2337.01
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,295.05,53.67,3.4,4.0,8812.8,4562,35.02000,35.02,0,762.33
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,295.05,53.67,3.4,4.0,16578.0,4562,35.02000,35.02,0,1481.33
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,295.05,53.67,3.4,4.0,0.0,4562,35.02000,35.02,0,0.00

In [19]:
def tf(compo_foyer):
    if compo_foyer=="Personne seule":
        return 0.0283
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 0.0315
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 0.0270
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 0.0238
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 0.0201
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 0.0185
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 0.0185-0.0006
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 0.0185-0.0006-0.0006

In [22]:
df['TF'] = df['Composition foyer demandeur'].apply(tf)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,C,P1,P2,R,R0,P0,35.02,0,Rp,TF
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,77.99,3.4,4.0,1134.0,7969,45.77335,35.02,0,27.01,0.0238
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,53.67,3.4,4.0,12171.6,4562,35.02000,35.02,0,1073.33,0.0283
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,102.31,3.4,4.0,0.0,8581,57.75835,35.02,0,0.00,0.0185
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,65.83,3.4,4.0,0.0,7793,39.78085,35.02,0,0.00,0.0270
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,53.67,3.4,4.0,15228.0,6534,35.02000,35.02,0,1356.33,0.0315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,53.67,3.4,4.0,0.0,4562,35.02000,35.02,0,0.00,0.0283
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,77.99,3.4,4.0,26082.0,7969,35.02000,35.02,0,2337.01,0.0238
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,53.67,3.4,4.0,8812.8,4562,35.02000,35.02,0,762.33,0.0283
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,53.67,3.4,4.0,16578.0,4562,35.02000,35.02,0,1481.33,0.0283
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,53.67,3.4,4.0,0.0,4562,35.02000,35.02,0,0.00,0.0283

In [23]:
def lr(compo_foyer):
    if compo_foyer=="Personne seule":
        return 257.14
    elif compo_foyer=="Au moins 2 cotitulaires":
        return 314.74
    elif (compo_foyer=="Au moins 2 cotitulaires avec une personne à charge" or compo_foyer=="Pers.seule avec 1 pers. à charge") :
        return 354.17
    elif (compo_foyer=="Pers.seule avec 2 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 2 personnes à charge"):
        return 354.17+51.54
    elif (compo_foyer=="Pers.seule avec 3 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 3 personnes à charge"):
        return 354.17+51.54+51.54
    elif (compo_foyer=="Pers.seule avec 4 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 4 personnes à charge"):
        return 17+51.54+51.54+51.54
    elif (compo_foyer=="Pers.seule avec 5 pers. à charge" or compo_foyer=="Au moins 2 cotitulaires avec 5 personnes à charge"):
        return 354.17+51.54+51.54+51.54+51.54
    elif (compo_foyer=="Personne seule avec 6 pers. à charge ou plus" or compo_foyer=="Au moins 2 cotitulaires avec 6 personnes à charge ou plus"):
        return 354.17+51.54+51.54+51.54+51.54+51.54

In [24]:
df['LR'] = df['Composition foyer demandeur'].apply(lr)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,P1,P2,R,R0,P0,35.02,0,Rp,TF,LR
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,3.4,4.0,1134.0,7969,45.77335,35.02,0,27.01,0.0238,405.71
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,3.4,4.0,12171.6,4562,35.02000,35.02,0,1073.33,0.0283,257.14
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,3.4,4.0,0.0,8581,57.75835,35.02,0,0.00,0.0185,171.62
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,3.4,4.0,0.0,7793,39.78085,35.02,0,0.00,0.0270,354.17
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,3.4,4.0,15228.0,6534,35.02000,35.02,0,1356.33,0.0315,314.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,3.4,4.0,0.0,4562,35.02000,35.02,0,0.00,0.0283,257.14
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,3.4,4.0,26082.0,7969,35.02000,35.02,0,2337.01,0.0238,405.71
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,3.4,4.0,8812.8,4562,35.02000,35.02,0,762.33,0.0283,257.14
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,3.4,4.0,16578.0,4562,35.02000,35.02,0,1481.33,0.0283,257.14
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,3.4,4.0,0.0,4562,35.02000,35.02,0,0.00,0.0283,257.14

In [26]:
df['RL']=df['L']/df['LR']
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,P2,R,R0,P0,35.02,0,Rp,TF,LR,RL
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,4.0,1134.0,7969,45.77335,35.02,0,27.01,0.0238,405.71,1.135096
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,4.0,12171.6,4562,35.02000,35.02,0,1073.33,0.0283,257.14,1.147429
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,4.0,0.0,8581,57.75835,35.02,0,0.00,0.0185,171.62,3.363244
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,4.0,0.0,7793,39.78085,35.02,0,0.00,0.0270,354.17,1.135556
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,4.0,15228.0,6534,35.02000,35.02,0,1356.33,0.0315,314.74,1.130616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,4.0,0.0,4562,35.02000,35.02,0,0.00,0.0283,257.14,1.147429
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,4.0,26082.0,7969,35.02000,35.02,0,2337.01,0.0238,405.71,0.756698
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,4.0,8812.8,4562,35.02000,35.02,0,762.33,0.0283,257.14,1.147429
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,4.0,16578.0,4562,35.02000,35.02,0,1481.33,0.0283,257.14,1.147429
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,4.0,0.0,4562,35.02000,35.02,0,0.00,0.0283,257.14,1.147429

In [28]:
df['C1']=0

def c1(rl):
    if rl>0.75:
        return 0.3
    else:
        return 0

df['C1'] = df['RL'].apply(c1)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,R,R0,P0,35.02,0,Rp,TF,LR,RL,C1
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,1134.0,7969,45.77335,35.02,0,27.01,0.0238,405.71,1.135096,0.3
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,12171.6,4562,35.02000,35.02,0,1073.33,0.0283,257.14,1.147429,0.3
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,0.0,8581,57.75835,35.02,0,0.00,0.0185,171.62,3.363244,0.3
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,0.0,7793,39.78085,35.02,0,0.00,0.0270,354.17,1.135556,0.3
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,15228.0,6534,35.02000,35.02,0,1356.33,0.0315,314.74,1.130616,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,0.0,4562,35.02000,35.02,0,0.00,0.0283,257.14,1.147429,0.3
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,26082.0,7969,35.02000,35.02,0,2337.01,0.0238,405.71,0.756698,0.3
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,8812.8,4562,35.02000,35.02,0,762.33,0.0283,257.14,1.147429,0.3
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,16578.0,4562,35.02000,35.02,0,1481.33,0.0283,257.14,1.147429,0.3
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,0.0,4562,35.02000,35.02,0,0.00,0.0283,257.14,1.147429,0.3

In [29]:
df['C2']=0

def c2(rl):
    if rl>0.45 and rl<=0.75 :
        return 0.0045
    elif rl>0.75:
        return 0.0068
    else:
        return 0

df['C2'] = df['RL'].apply(c2)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,R0,P0,35.02,0,Rp,TF,LR,RL,C1,C2
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,7969,45.77335,35.02,0,27.01,0.0238,405.71,1.135096,0.3,0.0068
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,4562,35.02000,35.02,0,1073.33,0.0283,257.14,1.147429,0.3,0.0068
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,8581,57.75835,35.02,0,0.00,0.0185,171.62,3.363244,0.3,0.0068
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,7793,39.78085,35.02,0,0.00,0.0270,354.17,1.135556,0.3,0.0068
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,6534,35.02000,35.02,0,1356.33,0.0315,314.74,1.130616,0.3,0.0068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,4562,35.02000,35.02,0,0.00,0.0283,257.14,1.147429,0.3,0.0068
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,7969,35.02000,35.02,0,2337.01,0.0238,405.71,0.756698,0.3,0.0068
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,4562,35.02000,35.02,0,762.33,0.0283,257.14,1.147429,0.3,0.0068
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,4562,35.02000,35.02,0,1481.33,0.0283,257.14,1.147429,0.3,0.0068
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,4562,35.02000,35.02,0,0.00,0.0283,257.14,1.147429,0.3,0.0068

In [30]:
df['C3']=0

def c3(rl):
    if rl>0.45 and rl<=0.75 :
        return 0.45
    elif rl>0.75:
        return 0.75
    else:
        return 0

df['C3'] = df['RL'].apply(c3)
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,P0,35.02,0,Rp,TF,LR,RL,C1,C2,C3
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,45.77335,35.02,0,27.01,0.0238,405.71,1.135096,0.3,0.0068,0.75
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,35.02000,35.02,0,1073.33,0.0283,257.14,1.147429,0.3,0.0068,0.75
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,57.75835,35.02,0,0.00,0.0185,171.62,3.363244,0.3,0.0068,0.75
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,39.78085,35.02,0,0.00,0.0270,354.17,1.135556,0.3,0.0068,0.75
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,35.02000,35.02,0,1356.33,0.0315,314.74,1.130616,0.3,0.0068,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,35.02000,35.02,0,0.00,0.0283,257.14,1.147429,0.3,0.0068,0.75
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,35.02000,35.02,0,2337.01,0.0238,405.71,0.756698,0.3,0.0068,0.75
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,35.02000,35.02,0,762.33,0.0283,257.14,1.147429,0.3,0.0068,0.75
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,35.02000,35.02,0,1481.33,0.0283,257.14,1.147429,0.3,0.0068,0.75
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,35.02000,35.02,0,0.00,0.0283,257.14,1.147429,0.3,0.0068,0.75

In [31]:
df['TL']=df['RL']-df['C3']
df['TL']= df['C2']*df['TL']
df['TL']= 0.0045*df['C1'] + df['TL']

#TL=0.0045*C1+C2*(RL-C3)

In [32]:
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,35.02,0,Rp,TF,LR,RL,C1,C2,C3,TL
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,35.02,0,27.01,0.0238,405.71,1.135096,0.3,0.0068,0.75,0.003969
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,35.02,0,1073.33,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,35.02,0,0.00,0.0185,171.62,3.363244,0.3,0.0068,0.75,0.019120
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,35.02,0,0.00,0.0270,354.17,1.135556,0.3,0.0068,0.75,0.003972
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,35.02,0,1356.33,0.0315,314.74,1.130616,0.3,0.0068,0.75,0.003938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,35.02,0,0.00,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,35.02,0,2337.01,0.0238,405.71,0.756698,0.3,0.0068,0.75,0.001396
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,35.02,0,762.33,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,35.02,0,1481.33,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,35.02,0,0.00,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053

In [33]:
df['Tp']=df['TL']+ df['TF']

In [34]:
df['Pp']=df['Tp']*df['Rp']
df['Pp']=df['Pp'] + df['P0']
df

,Numéro Unique,RM Moyennes,Ressources imposables mensuelles moyennes (RI),Prestations familiales et sociales mensuelles moyennes (PFS),Ri + PFS,région,Date création demande,Age demandeur,Situation familiale,Code département logement actuel,...,Rp,TF,LR,RL,C1,C2,C3,TL,Tp,Pp
0,111011473621594041,1094.0,105.0,989.0,1094.0,Alsace,2014-01-10,43.0,Marié (e),68.0,...,27.01,0.0238,405.71,1.135096,0.3,0.0068,0.75,0.003969,0.027769,46.523381
1,111011596527675056,1127.0,1127.0,0.0,1127.0,Alsace,2015-01-26,24.0,Célibataire,67.0,...,1073.33,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,69.744930
2,111011624892175056,1501.0,0.0,1501.0,1501.0,Alsace,2016-01-20,47.0,Marié (e),67.0,...,0.00,0.0185,171.62,3.363244,0.3,0.0068,0.75,0.019120,0.037620,57.758350
3,1110117567829GDPUB,674.0,0.0,674.0,674.0,Alsace,2017-01-14,27.0,Divorcé (e),68.0,...,0.00,0.0270,354.17,1.135556,0.3,0.0068,0.75,0.003972,0.030972,39.780850
4,1110117576292AL018,1410.0,1410.0,0.0,1410.0,Alsace,2017-01-25,30.0,Concubin (e),67.0,...,1356.33,0.0315,314.74,1.130616,0.3,0.0068,0.75,0.003938,0.035438,83.085876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181616,175120708787700002,433.0,0.0,433.0,433.0,Pays de la Loire,2007-12-05,37.0,Célibataire,44.0,...,0.00,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,35.020000
181617,175120725745300002,2415.0,2415.0,0.0,2415.0,Picardie,2007-12-17,54.0,Célibataire,60.0,...,2337.01,0.0238,405.71,0.756698,0.3,0.0068,0.75,0.001396,0.025196,93.902246
181618,175120901070000002,1225.0,816.0,409.0,1225.0,Picardie,2009-12-15,29.0,Célibataire,60.0,...,762.33,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,59.683297
181619,175121022516400002,1535.0,1535.0,0.0,1535.0,Pays de la Loire,2010-12-20,72.0,Divorcé (e),49.0,...,1481.33,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,82.944758
181620,211011233353775B02,924.0,0.0,924.0,924.0,Picardie,2009-09-03,49.0,Célibataire,60.0,...,0.00,0.0283,257.14,1.147429,0.3,0.0068,0.75,0.004053,0.032353,35.020000

In [68]:
base['APL']=base['Loyer éligible'] + base['Montant forfaitaire au titre des charges']-base['Participation personnelle du ménage']

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\3801738382.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['APL']=base['Loyer éligible'] + base['Montant forfaitaire au titre des charges']-base['Participation personnelle du ménage']

In [69]:
base['P1']=3.4*base['Montant loyer mensuel du logement attribué\n']
base['P2']=4*base['Montant loyer mensuel du logement attribué\n']

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\679197961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['P1']=3.4*base['Montant loyer mensuel du logement attribué\n']
C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\679197961.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['P2']=4*base['Montant loyer mensuel du logement attribué\n']

In [71]:
base['APL1']=(base['P2']*base['Montant loyer mensuel du logement attribué\n']-base['Loyer éligible'])/((base['P2']-base['P1'])*base['Montant loyer mensuel du logement attribué\n'])*base['APL']
#replace APL=(P2*Lp-L)/((P2-P1)*Lp)*APL if L>P1 & L<=P2

C:\Users\arceb\AppData\Local\Temp\ipykernel_17184\837855797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['APL1']=(base['P2']*base['Montant loyer mensuel du logement attribué\n']-base['Loyer éligible'])/((base['P2']-base['P1'])*base['Montant loyer mensuel du logement attribué\n'])*base['APL']

In [79]:
base

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,...,C1,C2,C3,TL,Taux de prise en compte des ressources des ménages (Tp),Participation personnelle du ménage,APL,P1,P2,APL1
0,300.0,556.0,1.0,308.0,Personne seule,0,175037900427000002,295.05,0.00,53.67,...,0.0,0.0000,0.00,0.000000,0.028300,75.851240,-22.181240,0.0,0,NaN
1,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,503.432726,-154.712726,1013.2,1192,-1030.561455
2,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,335.018448,13.701552,1264.8,1488,91.294993
3,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,...,0.3,0.0068,0.75,0.003938,0.035438,1156.425992,-746.905992,2754.0,3240,-4978.698111
4,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,985.964092,-637.244092,2128.4,2504,-4247.494292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153709,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,...,0.3,0.0068,0.75,0.002105,0.033605,303.591091,21.078909,921.4,1084,140.396420
153710,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,...,0.3,0.0068,0.75,0.003205,0.031505,228.145443,88.524557,894.2,1052,589.602724
153711,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,515.312571,-166.592571,1604.8,1888,-1110.249423
153712,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,...,0.3,0.0068,0.75,0.002032,0.025832,802.098280,-379.108280,1173.0,1380,-2525.557094
153713,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,...,0.3,0.0068,0.75,0.003972,0.030972,570.098307,-102.088307,1485.8,1748,-680.230385

In [87]:
base1=base.dropna()
base1 = base1.reset_index(drop=True)
base1

,Montant maxi (loyer+charges) supportable,Ressources mensuelles du foyer,Nb unités de consommation du foyer,Loyer montant mensuel,Composition foyer demandeur,Montant loyer mensuel du logement attribué\n,Numéro Unique,Plafond loyer,Loyer éligible,Montant forfaitaire au titre des charges,...,C1,C2,C3,TL,Taux de prise en compte des ressources des ménages (Tp),Participation personnelle du ménage,APL,P1,P2,APL1
0,400.0,1763.0,1.0,800.0,Personne seule,298,175118000728300002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,503.432726,-154.712726,1013.2,1192,-1030.561455
1,300.0,1281.0,1.0,802.0,Personne seule,372,211048217550092024,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,335.018448,13.701552,1264.8,1488,91.294993
2,700.0,3535.0,1.5,694.0,Au moins 2 cotitulaires,810,175108301617300002,355.85,355.85,53.67,...,0.3,0.0068,0.75,0.003938,0.035438,1156.425992,-746.905992,2754.0,3240,-4978.698111
3,1000.0,3144.0,1.0,878.0,Personne seule,626,175128420982700002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,985.964092,-637.244092,2128.4,2504,-4247.494292
4,0.0,1819.0,1.0,679.0,Personne seule,441,175018604471600002,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,522.999530,-174.279530,1499.4,1764,-1161.422864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113706,354.0,1345.0,1.5,469.0,Au moins 2 cotitulaires,271,1111218129847GDPUB,355.85,271.00,53.67,...,0.3,0.0068,0.75,0.002105,0.033605,303.591091,21.078909,921.4,1084,140.396420
113707,400.0,990.0,1.0,388.0,Personne seule,263,111121812788778498,295.05,263.00,53.67,...,0.3,0.0068,0.75,0.003205,0.031505,228.145443,88.524557,894.2,1052,589.602724
113708,472.0,1797.0,1.0,560.0,Personne seule,472,111121812792310122,295.05,295.05,53.67,...,0.3,0.0068,0.75,0.004053,0.032353,515.312571,-166.592571,1604.8,1888,-1110.249423
113709,800.0,3484.0,2.1,592.0,Au moins 2 cotitulaires avec 2 personnes à charge,345,111121813038177438,460.52,345.00,77.99,...,0.3,0.0068,0.75,0.002032,0.025832,802.098280,-379.108280,1173.0,1380,-2525.557094
113710,500.0,2307.0,1.8,460.0,Au moins 2 cotitulaires avec une personne à ch...,437,111121813209910389,402.18,402.18,65.83,...,0.3,0.0068,0.75,0.003972,0.030972,570.098307,-102.088307,1485.8,1748,-680.230385

In [89]:
base1.rename(columns={'Montant loyer mensuel du logement attribué\n': 'Montant loyer mensuel du logement attribue'}, inplace=True)

In [90]:
def apl(l):
    if l>base1[base1['P1']] and l<=base1[base1['P2']] :
        return base1['APL1']
    elif l>base1[base1['P2'] * base1['Montant loyer mensuel du logement attribue']]:
        return 0
    else:
        return 0

base1['APL'] = base1['Montant loyer mensuel du logement attribue'].apply(apl)
base1

KeyError: "None of [Float64Index([1013.1999999999999,             1264.8,             2754.0,\n                          2128.4, 1499.3999999999999, 2369.7999999999997,\n              2216.7999999999997, 1414.3999999999999,             2631.6,\n                          3070.2,\n              ...\n                          2142.0,            33996.6,             1003.0,\n                          2400.4,             2713.2,              921.4,\n               894.1999999999999,             1604.8,             1173.0,\n                          1485.8],\n             dtype='float64', length=113711)] are in the [columns]"

In [82]:
#replace APL=(P2*Lp-L)/((P2-P1)*Lp)*APL if L>P1 & L<=P2
def apl(l):
    if base[l] > base[base['P1']] and l <= base[base['P2']]:
        return base['APL1']
    elif base[l] > base[base['P2'] * base['Montant loyer mensuel du logement attribué\n']]:
        return 0
    else:
        return 0


base['APL'] = base['Montant loyer mensuel du logement attribué\n'].apply(apl)
base

KeyError: 0

In [ ]:
#replace APL=(P2*Lp-L)/((P2-P1)*Lp)*APL if L>P1 & L<=P2
def apl(l):
    if l > base[base['P1']] and l <= base[base['P2']]:
        return base['APL1']
    elif l > base[base['P2'] * base['Montant loyer mensuel du logement attribué\n']]:
        return 0
    else:
        return 0


base['APL'] = base['Montant loyer mensuel du logement attribué\n'].apply(apl)
base